INSERT INTO ra_interface_lines_all 
            ( BU_NAME, 
                        SOURCE_SYSTEM, 
                        CUST_TRX_TYPE_NAME, 
                        TERM_NAME, 
                        TRX_NUMBER, 
                        BILL_CUSTOMER_ACCOUNT_NUMBER, 
                        BILL_CUSTOMER_SITE_NUMBER, 
                        SHIP_CUSTOMER_ACCOUNT_NUMBER, 
                        SHIP_PARTY_SITE_NUMBER, 
                        line_type, 
                        description, 
                        currency_code, 
                        conversion_type, 
                        conversion_rate, 
                        amount, 
                        quantity, 
                        unit_selling_price, 
                        INTERFACE_LINE_CONTEXT, 
                        attribute1, 
                        attribute2, 
                        uom_code, 
                        default_taxation_country, 
                        taxable_flag, 
                        amount_includes_tax_flag 
            ) 
            VALUES 
            ( 
                        'US1 Business Unit', 
                        'GSE External Source', 
                        'Invoice', 
                        'Immediate', 
                        2237673068, 
                        16080, 
                        1032, 
                        16080, 
                        1032, 
                        'LINE', 
                        'Standard Product', 
                        'USD', 
                        'User', 
                        1, 
                        81579, 
                        1, 
                        81579, 
                        'EXTERNAL_SOURCE', 
                        'lh3010', 
                        'Line1', 
                        'Ea', 
                        'US', 
                        'N', 
                        'N' 
            );